# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN='d35b3eff-49e8-44c1-8cf4-27501ed6033f'

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту emelyanoff94@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - emelyanoff94@gmail.com
    on_success: never # default: change
    on_failure: always # default: always